! Copyright (c) 2024 The YAC Authors
!
! SPDX-License-Identifier: BSD-3-Clause

MODULE toy_ocn

  USE mpi
  USE yac
  USE yac_utils, ONLY : yac_test_gulfstream_c
  USE toy_common, ONLY : read_icon_grid, nsteps, define_fields, &
                         send_field, receive_field, max_char_length

  IMPLICIT NONE

  PRIVATE

  INTEGER :: t, ierror

  ! Basic string paramters
  CHARACTER(LEN=max_char_length), PARAMETER :: yaml_filename = "input/coupling.yaml"
  CHARACTER(LEN=max_char_length), PARAMETER :: grid_filename = "grids/GEIA_MPIC1.0_X_bioland_NH3_2000-2000.nc"
  CHARACTER(LEN=max_char_length), PARAMETER :: comp_name = "ocn_comp"
  CHARACTER(LEN=max_char_length), PARAMETER :: grid_name = "ocn_grid"
  character(len = 5000) :: attr_grid_total
  
  ! IDs and communicator generated by YAC
  INTEGER :: comp_id, comp_comm ! = MPI_COMM_WORLD
  INTEGER :: comp_rank
  INTEGER :: grid_id
  INTEGER :: cell_point_id
  INTEGER :: field_taux_id, field_tauy_id
  INTEGER :: field_sfwflx_id
  INTEGER :: field_sftemp_id
  INTEGER :: field_thflx_id
  INTEGER :: field_iceatm_id, field_iceoce_id
  INTEGER :: field_sst_id
  INTEGER :: field_oceanu_id, field_oceanv_id
  integer(kind = 4) :: i
  
  ! Basic decomposed grid information
  INTEGER(kind = 4)             :: num_vertices_lon, num_vertices_lat, num_vertices
  INTEGER(kind = 4)             :: num_cells, num_vertices_per_cell

  DOUBLE PRECISION, ALLOCATABLE :: x_vertices(:), y_vertices(:)
  DOUBLE PRECISION, ALLOCATABLE :: x_cells(:), y_cells(:)

  integer, allocatable     :: global_cell_ids(:)

  ! Buffer for field data
  DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: &
       taux, tauy, sfwflx, sftemp, thflx, iceatm, sst, oceanu, oceanv, iceoce

  PUBLIC :: main_ocn

CONTAINS

  SUBROUTINE main_ocn(comm)

    INTEGER, INTENT(IN) :: comm
    integer, dimension(2) :: cyclic = (/1, 0 /)
    character(len = 5000) :: grid_metadata

    comp_comm = comm

    ! Read coupling configuration file
    CALL yac_fread_config_yaml(yaml_filename)

    ! Define local component
    CALL yac_fdef_comp(comp_name, comp_id)

    ! Retrieve communicator for OCN component
    CALL yac_fget_comp_comm(comp_id, comp_comm)

    CALL MPI_Comm_rank(comp_comm, comp_rank, ierror)

    ! Define local part of the grid
    call read_grid_from_netcdf(trim(grid_filename), num_vertices_lon, num_vertices_lat, num_cells, &
         x_vertices, y_vertices, x_cells, y_cells, attr_grid_total)
    num_vertices_per_cell = 4

    allocate(global_cell_ids(num_cells))

    ! Define the grid for YAC
    cyclic = (/ 1,0/)
    CALL yac_fdef_grid( &
         grid_name, (/ num_vertices_lon, num_vertices_lat /), cyclic, &
         x_vertices, y_vertices, grid_id )
    ! Interface for yac_fdef_grid_reg2d_dble 

    ! Define location of the actual data (on cell centers)
    !    write(*, *)
    !    write(*, *) "OCN: Before YAC_FDEF_POINTS"

    write( grid_metadata,'(A)') attr_grid_total
    CALL yac_fdef_grid_metadata(grid_name, grid_metadata) 
!    call yac_fdef_field_metadata(comp_name, grid_name, field_name, 

    
    CALL yac_fdef_points ( &
         grid_id, (/ num_vertices_lon, num_vertices_lat /), YAC_LOCATION_CORNER, &
         x_vertices, y_vertices, cell_point_id )

!    CALL yac_fdef_points ( &
!         grid_id, (/ num_vertices_lon-1, num_vertices_lat-1 /), YAC_LOCATION_CELL, &
!         x_cells, y_cells, cell_point_id )

!    write(*, *)
!    write(*, *) "OCN: After YAC_FDEF_POINTS"

    ! Set global cell ids
    CALL yac_fset_global_index(global_cell_ids, YAC_LOCATION_CELL, grid_id)

    ! Set mask for cell centers
    ! CALL yac_fset_mask(cell_sea_land_mask < 0, cell_point_id)

    ! Define fields
    CALL define_fields( &
         comp_id, cell_point_id, field_taux_id, field_tauy_id, field_sfwflx_id, &
         field_sftemp_id, field_thflx_id, field_iceatm_id, field_sst_id, &
         field_oceanu_id, field_oceanv_id, field_iceoce_id)

    ! Complete definitions and compute interpolations
    CALL yac_fenddef()

    ! Initialise fields
    CALL init_fields()

    ! Execute model time loop
    DO t = 1, nsteps

       ! Simulate ocn timestep
       CALL sim_ocn_timestep(t)

       ! Exchange data with atm component
       CALL couple_to_atm()

    END DO ! time loop

  END SUBROUTINE main_ocn

  SUBROUTINE init_fields()

    INTEGER :: i

    ! Allocate output field buffers
    ALLOCATE( &
      sst(num_vertices, 1), oceanu(num_vertices, 1), oceanv(num_vertices, 1), &
      iceoce(num_vertices, 5))

    ! Initialise output field buffer with dummy data
!    DO i = 1, num_cells
!      sst(i,1) = yac_test_gulfstream_c(x_cells(i), y_cells(i))
!    END DO
    sst(:, 1) = 0.0d0
    oceanu(:,1) = 120.0d0
    oceanv(:,1) = 130.0d0
    iceoce(:,1) = 140.1d0
    iceoce(:,2) = 140.2d0
    iceoce(:,3) = 140.3d0
    iceoce(:,4) = 140.4d0
    iceoce(:,5) = 140.5d0

    ! Allocate input field buffers
    ALLOCATE( &
      taux(num_vertices, 2), tauy(num_vertices, 2), sfwflx(num_vertices, 3), &
      sftemp(num_vertices, 1), thflx(num_vertices, 4), iceatm(num_vertices, 4))

    ! Initialise input field buffer with zero
    taux(:,1) = 0.0d0
    taux(:,2) = 0.0d0
    tauy(:,1) = 0.0d0
    tauy(:,2) = 0.0d0
    sfwflx(:,1) = 0.0d0
    sfwflx(:,2) = 0.0d0
    sfwflx(:,3) = 0.0d0
    sftemp(:,1) = 0.0d0
    thflx(:,1) = 0.0d0
    thflx(:,2) = 0.0d0
    thflx(:,3) = 0.0d0
    thflx(:,4) = 0.0d0
    iceatm(:,1) = 0.0d0
    iceatm(:,2) = 0.0d0
    iceatm(:,3) = 0.0d0
    iceatm(:,4) = 0.0d0

  END SUBROUTINE init_fields

  SUBROUTINE sim_ocn_timestep(timestep)

    INTEGER, INTENT(IN) :: timestep

    ! Do an ocean timestep

    ! ...

    CALL MPI_Barrier(comp_comm, ierror)
    IF (comp_rank == 0) &
      PRINT "('--- ',A3,' timestep ',I2,' ---')", comp_name, timestep

  END SUBROUTINE sim_ocn_timestep

  SUBROUTINE couple_to_atm()

    ! --------------------
    ! Send fields to ocean
    ! --------------------

    ! Send sea surface temperature
    CALL send_field(field_sst_id, sst)

    ! Send zonal velocity
    CALL send_field(field_oceanu_id, oceanu)

    ! Send meridional velocity
    CALL send_field(field_oceanv_id, oceanv)

    ! Send Ice thickness, concentration, T1 and T2
    CALL send_field(field_iceoce_id, iceoce)

    ! -------------------------
    ! Receive fields from ocean
    ! -------------------------

    ! Recieve meridional wind stress
    CALL receive_field(comp_name, field_taux_id, taux)

    ! Recieve zonal  wind stress
    CALL receive_field(comp_name, field_tauy_id, tauy)

    ! Recieve surface fresh water flux
    CALL receive_field(comp_name, field_sfwflx_id, sfwflx)

    ! Recieve surface temperature
    CALL receive_field(comp_name, field_sftemp_id, sftemp)

    ! Recieve total heat flux
    CALL receive_field(comp_name, field_thflx_id, thflx)

    ! Recieve ice temperatures and melt potential
    CALL receive_field(comp_name, field_iceatm_id, iceatm)

  END SUBROUTINE couple_to_atm


    ! ===================== subroutine readgrid_from_netcdf =========================
  subroutine read_grid_from_netcdf(filename, num_vertices_lon, num_vertices_lat, num_cells, &
       x_vertices, y_vertices, x_cells, y_cells, attr_grid_total)
    use netcdf
    implicit none

    character(len = *) :: filename
    character(len = 200) :: name
    character(len = 5000) :: attr_grid_total

    integer :: ncid, status, xtype, ndim, nvar, natt, natts
    integer :: len, k, ndims, k_un
    integer(kind = 4), intent(out) :: num_vertices_lon, num_vertices_lat, num_cells
    integer, allocatable, dimension(:) :: dimids

    real(kind = 8) :: correction_value_lon, correction_value_lat
    real(kind = 8), allocatable, dimension(:) :: x_vertices, y_vertices
    real(kind = 8), allocatable, dimension(:) :: x_cells, y_cells
    
    ! Open netCDF file
    write(*, *)
    write(*, *) "----- OCN: Open ocean netCDF file -----"
    status = nf90_open(trim(filename), nf90_nowrite, ncid)
    if(status /= nf90_noerr) then
       write(*, *) 'OCN: could not open (ocean): ', filename
       write(*, *) status
       write(*, *) '***** OCN: Unable to find netCDF file (ocean) *****'
       stop
    endif

    ! Inquiry of the nuber of variables, etc
    write(*, *)
    write(*, *) "----- OCN: Inquire number of dimensions, variables, etc -----"
    status = nf90_inquire(ncid, ndim, nvar, natt, k_un)
    if (status /= nf90_noerr) then
       write(*, *) 'OCN: nf90_inquire error (ocean)'
       write(*, *) status
       write(*, *) '***** OCN: Unable to read number of variables, etc (ocean) *****'
       stop
    endif

    ! Output of the dimensions
    allocate(dimids(ndim))

    write(*, *)
    write(*, *) "----- OCN: Output of dimensions id, length and name -----"
    do k = 1, ndim
       status = nf90_inquire_dimension(ncid, k, name, len)
       if (status /= nf90_noerr) then
          write(*, *) "n90_inquire_dimension error (ocean)" 
          write(*, *) status
          stop
       endif

       ! read number vertices in longitude directions (vertex is midpoint of cell)
       if(index(trim(name), 'lon') /= 0) then
          num_vertices_lon = len
       end if

       ! read number vertices in lattitude directions (vertex is midpoint of cell)
       if(index(trim(name), 'lat') /= 0) then
          num_vertices_lat = len
       end if
    enddo

    allocate(x_cells(num_vertices_lon))
    allocate(y_cells(num_vertices_lat))

    ! Number of cells is product of vertices in lat and lon direction because
    ! usually the coordinates are centered in an element
    num_cells = num_vertices_lon * num_vertices_lat

    ! Now correction to number of vertices if vertex is on a real node and not in cell center
    num_vertices_lon = num_vertices_lon + 1
    num_vertices_lat = num_vertices_lat + 1 

    ! Output of the variables
!    write(*, *)
!    write(*, *) "OCN: ----- Variables -----"
    attr_grid_total = ''
    do k = 1, nvar
       name = ''
       status = nf90_inquire_variable(ncid, k, name, xtype, ndims, dimids, natts)
       if (status /= nf90_noerr) then
          write(*, *) "OCN: n90_inquire_variable error"
          write(*, *) status
          stop
       endif

       if(index(trim(name), 'lon') /= 0) then
          allocate(x_vertices(num_vertices_lon))
          
          status = nf90_get_var( ncid, k, x_cells ) 
          if (status /= nf90_noerr) then
             write(*, *) "***** n90_get_var error *****"
             write(*, *) "status", status
             stop 
          endif

          ! Correction
          ! Assumption:
          !    - whole erath (360 degrees laongitude, 180 degrees latitude)
          !    - cell centered and corner centered coordinates
          correction_value_lon = 360.0 / ((num_vertices_lon - 1) * 2)
          write(*, *) "OCN: correction_value_lon: ", correction_value_lon
          if( abs( x_cells(1) - (-180.0) ) > 1e-10) then
             write(*, *) "OCN: Cell centered values"
             do i = 1, num_vertices_lon - 1
                x_vertices(i) = x_cells(i) - correction_value_lon  ! 0.5
             end do
          else
             write(*, *) "OCN: Corner Centered values"
          end if
          x_vertices(num_vertices_lon) = 180.0
          write(*, *) x_vertices

          if(natts > 0) then
             write(* ,*) 'OCN: ==== data attributes ===='
             call parse_attr_list(ncid, natts, k, attr_grid_total)
             write(*, *)
             write(*, *) "OCN: attr_grid_total (lon): ", trim(attr_grid_total)
             write(*, *)
          endif
       end if

       if(index(trim(name), 'lat') /= 0) then
          allocate(y_vertices(num_vertices_lat))

          status = nf90_get_var( ncid, k, y_cells ) 
          if (status /= nf90_noerr) then
             write(*, *) "OCN: ***** n90_get_var error (ocean) *****"
             write(*, *) "OCN: status: ", status
             stop 
          endif

                    ! Corection
          ! Assumption:
          !    - whole erath (360 degrees laongitude, 180 degrees latitude)
          !    - cell and corner centered coordinates
          correction_value_lat = 180.0 / ((num_vertices_lat - 1) * 2)
          write(*, *) "OCN: correction_value_lat: ", correction_value_lat
          if( (y_cells(1) - (-90.0)) > 1e-10) then
             write(*, *) "OCN: Cell centered values"
             do i = 1, num_vertices_lat - 1
                y_vertices(i) = y_cells(i) - correction_value_lat  !0.5
             end do
          else
             write(*, *) "OCN: Cell centered values"
          end if
          y_vertices(num_vertices_lat) = 90.0

          if(natts > 0) then
!             write(* ,*) 'OCN: ==== data attributes ===='
             call parse_attr_list(ncid, natts, k, attr_grid_total)
             write(*, *)
             write(*, *) "OCN: attr_grid_total (lat): ", trim(attr_grid_total)
             write(*, *)
          endif
       end if
    enddo


! Allocate and fill the vertex arrays (for longitude and lattitude
    num_vertices = num_vertices_lon * num_vertices_lat
    
    ! Output of the attributes
    if(natt > 0) then
       call parse_attr_list(ncid, natt, nf90_global, attr_grid_total)
       write(*, *)
       write(*, *) "OCN: attr_grid_total (global): ", trim(attr_grid_total)
       write(*, *)
     endif

  end subroutine read_grid_from_netcdf

  !=============================================================================
  subroutine parse_attr_list( ncid, n_attr_loc, varid, attr_grid_total )
    use netcdf

    character(len = 1024) :: c1d, name
    character(len = 4096) :: attr_grid_total

    integer(kind = 4) :: ncid, n_attr_loc, varid
    integer(kind = 4) :: xtype, len, status
    integer(kind = 4) :: k, kk

    real(kind = 8) :: rval

    integer(kind = 4), allocatable, dimension(:) :: ivals
    real(kind = 8), allocatable, dimension(:) :: rvals

    do k = 1, n_attr_loc
       status = nf90_inq_attname(ncid, varid, k, name)
       status = nf90_inquire_attribute(ncid, varid, name, xtype, len, kk)

       if (xtype == NF90_CHAR) then
          if (len > 1024) then
             write(*,*) 'truncating attribute to length:', 1024
          endif
          status = nf90_get_att(ncid, varid, name, c1d )
          if (status /= 0) stop 'error calling get_att'
          name = trim(name)
          attr_grid_total = trim(attr_grid_total)

          write(attr_grid_total, '(A, "; ", A, " ", A)') trim(attr_grid_total), trim(name), trim(c1d)
          write(*, *) "OCN attrgrid_total (in subroutine): ", trim(attr_grid_total) 
       else if ( xtype == NF90_INT ) then
          write(*, *) "OCN: Attribute type is NF90_INT"
          if (len > 1) then
             allocate( ivals(len) )
             status = nf90_get_att(ncid, varid, name, ivals )
             if (status /= 0) stop "error calling get_att for integer array"
             deallocate( ivals )
          else
             status = nf90_get_att(ncid, varid, name, ivals )
             if (status /= 0) stop 'error calling get_att for integer'
          endif
          write(*, *) "OCN: xtype_attr NF90_INT: ", xtype
       else if( xtype == NF90_FLOAT ) then
          write(*, *) "OCN: Attribute type is NF90_FLOAT"
          if (len > 1) then
             allocate( rvals(len) )
             status = nf90_get_att(ncid, varid, name, rvals )
             if (status /= 0) stop 'error calling get_att for real array'
             deallocate( rvals )
          else
             status = nf90_get_att(ncid, varid, name, rval )
             if(status /= 0) stop "error calling get_att for real"
          endif
       else if( xtype == NF90_DOUBLE ) then
          write(*, *) "OCN: Attribute type is NF90_DOUBLE"
          if (len > 1) then
             allocate( rvals(len) )
             status = nf90_get_att(ncid, varid, name, rvals )
             if (status /= 0) stop "error calling get_att for real array"
             deallocate( rvals )
          else
             status = nf90_get_att(ncid, varid, name, rval )
             if(status /= 0) stop "error calling get_att for real"
          endif
       endif
    enddo
  end subroutine parse_attr_list
END MODULE toy_ocn

PROGRAM main_ocn_program
  USE mpi
  USE yac
  USE toy_ocn, ONLY : main_ocn

  IMPLICIT NONE

  INTEGER :: ierror

  ! Initialise MPI
  CALL MPI_Init(ierror)

  ! Initialise the YAC
  CALL yac_finit()

  ! Run atmosphere model
  CALL main_ocn(MPI_COMM_WORLD)

  ! Finalise YAC
  CALL yac_ffinalize()

  ! Finalise MPI
  CALL MPI_Finalize(ierror)
END PROGRAM main_ocn_program
